serviceAccount:
  create: false
  name: fluent-bit

securityContext:
  runAsUser: 0
  seLinuxOptions:
    type: spc_t
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

# The rest is not required, just to simplify and use in the example
image:
  repository: registry.connect.redhat.com/calyptia/fluent-bit
  tag: 1.8.12

config:
  outputs: |
    [OUTPUT]
        Name stdout
        Match *
